[package]
name = "akame"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]
edition = "2021"

[dependencies]
redis = "0.8.0"
lazy_static = "1.0"
chrono = { git = "https://github.com/chronotope/chrono", rev = "1a0d47a3e58eeb44e2b5022547262650d1a7a436" }
